/*
 * generated by Xtext 2.20.0
 */
package at.bestsolution.jfr.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JFRMetaUiModule extends AbstractJFRMetaUiModule {

	public JFRMetaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
