/*
 * generated by Xtext 2.20.0
 */
package at.bestsolution.jfr.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class JFRMetaScopeProvider extends AbstractJFRMetaScopeProvider {

}
