/*
 * generated by Xtext 2.20.0
 */
package at.bestsolution.jfr.ide;

import at.bestsolution.jfr.JFRMetaRuntimeModule;
import at.bestsolution.jfr.JFRMetaStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JFRMetaIdeSetup extends JFRMetaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JFRMetaRuntimeModule(), new JFRMetaIdeModule()));
	}
	
}
