/*
 * generated by Xtext 2.20.0
 */
package at.bestsolution.jfr.web;

import at.bestsolution.jfr.JFRMetaRuntimeModule;
import at.bestsolution.jfr.JFRMetaStandaloneSetup;
import at.bestsolution.jfr.ide.JFRMetaIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class JFRMetaWebSetup extends JFRMetaStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JFRMetaRuntimeModule(), new JFRMetaIdeModule(), new JFRMetaWebModule()));
	}
	
}
