/*
 * generated by Xtext 2.20.0
 */
package at.bestsolution.jfr.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class JFRMetaWebModule extends AbstractJFRMetaWebModule {
}
