/*
 * generated by Xtext 2.20.0
 */
package at.bestsolution.jfr;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JFRMetaStandaloneSetup extends JFRMetaStandaloneSetupGenerated {

	public static void doSetup() {
		new JFRMetaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
